
	INSERT INTO [MEGASTAR MEDIA JV$Salary Input From HR]
	([Entry No_],
	[Period Code],
	[Deparment Code],
	[Posting Date],
	[Status],
	[Template Type],
	[HI],
	[Sales Incentive],
	[PIT],
	[Bonus],
	[OT],
	[SIE And HIE],
	[UIE],
	[SIC And HIC],
	[UIC],
	[Trade Union Employees],
	[Trade Union Company],
	[Salary],
	[Allowance Task],
	[Allowance Exp],
	[Allowance Meal],
	[Allowance Car],
	[Allowance Gas],
	[Allowance Telephone],
	[Allowance Price],
	[Allowance Housing],
	[Allowance Lang_ Education],
	[Allowance Service],
	[Allowance Come Back Home],
	[Allowance Professional],
	[Allowance Relocation],
	[Allowance 1],
	[Allowance 2],
	[Allowance 3],
	[Allowance 4],
	[Allowance 5],
	[Allowance 6],
	[Allowance 7],
	[Cost center code]
	)
	VALUES (
	@EntryNo ,
	@PeriodCode ,
	@Location ,
	@PostingDate ,
	@Status ,
	@TemplateType ,
	@HI ,
	@SalesIncentive ,
	@PIT ,
	@Bonus ,
	@OT ,
	@SIEAndHIE ,
	@UIE ,
	@SICAndHIC ,
	@UIC ,
	@TradeUnionEmployees ,
	@TradeUnionCompany ,
	@Salary ,
	@AllowanceTask ,
	@AllowanceExp ,
	@AllowanceMeal ,
	@AllowanceCar ,
	@AllowanceGas ,
	@AllowanceTelephone ,
	@AllowancePrice ,
	@AllowanceHousing ,
	@AllowanceEducation ,
	@AllowanceService ,
	@AllowanceComeBackHome ,
	@AllowanceProfessional ,
	@AllowanceRelocation ,
	@Allowance1 ,
	@Allowance2 ,
	@Allowance3 ,
	@Allowance4 ,
	@Allowance5 ,
	@Allowance6 ,
	@Allowance7 ,
	@CostCenter)