CREATE PROC TVC_PRI_SAL
	@EntryNo int,
	@PeriodCode varchar(20),
	@DepartmentCode varchar(10),
	@PostingDate datetime,
	@Status int,
	@TemplateType int,
	@HI decimal(38,20),
	@SalesIncentive decimal(38,20),
	@PIT decimal(38,20),
	@Bonus decimal(38,20),
	@OT decimal(38,20),
	@SIEAndHIE decimal(38,20),
	@UIE decimal(38,20),
	@SICAndHIC decimal(38,20),
	@UIC decimal(38,20),
	@TradeUnionEmployees decimal(38,20),
	@TradeUnionCompany decimal(38,20),
	@Salary decimal(38,20),
	@AllowanceTask decimal(38,20),
	@AllowanceExp decimal(38,20),
	@AllowanceMeal decimal(38,20),
	@AllowanceCar decimal(38,20),
	@AllowanceGas decimal(38,20),
	@AllowanceTelephone decimal(38,20),
	@AllowancePrice decimal(38,20),
	@AllowanceHousing decimal(38,20),
	@AllowanceEducation decimal(38,20),
	@AllowanceService decimal(38,20),
	@AllowanceComeBackHome decimal(38,20),
	@AllowanceProfessional decimal(38,20),
	@AllowanceRelocation decimal(38,20),
	@Allowance1 decimal(38,20),
	@Allowance2 decimal(38,20),
	@Allowance3 decimal(38,20),
	@Allowance4 decimal(38,20),
	@Allowance5 decimal(38,20),
	@Allowance6 decimal(38,20),
	@Allowance7 decimal(38,20)
AS
BEGIN
	INSERT INTO [MEGASTAR MEDIA JV$Salary Input From HR]
	([Entry No_],
	[Period Code],
	[Deparment Code],
	[Posting Date],
	[Status],
	[Template Type],
	[HI],
	[Sales Incentive],
	[PIT],
	[Bonus],
	[OT],
	[SIE And HIE],
	[UIE],
	[SIC And HIC],
	[UIC],
	[Trade Union Employees],
	[Trade Union Company],
	[Salary],
	[Allowance Task],
	[Allowance Exp],
	[Allowance Meal],
	[Allowance Car],
	[Allowance Gas],
	[Allowance Telephone],
	[Allowance Price],
	[Allowance Housing],
	[Allowance Lang_ Education],
	[Allowance Service],
	[Allowance Come Back Home],
	[Allowance Professional],
	[Allowance Relocation],
	[Allowance 1],
	[Allowance 2],
	[Allowance 3],
	[Allowance 4],
	[Allowance 5],
	[Allowance 6],
	[Allowance 7]
	)
	VALUES (
	@EntryNo ,
	@PeriodCode ,
	@DepartmentCode ,
	@PostingDate ,
	@Status ,
	@TemplateType ,
	@HI ,
	@SalesIncentive ,
	@PIT ,
	@Bonus ,
	@OT ,
	@SIEAndHIE ,
	@UIE ,
	@SICAndHIC ,
	@UIC ,
	@TradeUnionEmployees ,
	@TradeUnionCompany ,
	@Salary ,
	@AllowanceTask ,
	@AllowanceExp ,
	@AllowanceMeal ,
	@AllowanceCar ,
	@AllowanceGas ,
	@AllowanceTelephone ,
	@AllowancePrice ,
	@AllowanceHousing ,
	@AllowanceEducation ,
	@AllowanceService ,
	@AllowanceComeBackHome ,
	@AllowanceProfessional ,
	@AllowanceRelocation ,
	@Allowance1 ,
	@Allowance2 ,
	@Allowance3 ,
	@Allowance4 ,
	@Allowance5 ,
	@Allowance6 ,
	@Allowance7 )
END 